labels:
  platform: linux/amd64

when:
  event: [ push, tag ]

variables:
  - &emoji_build_image 'sc.cryxtal.org/ci-img/emoji-build:bookworm'
  - &sha256_image 'sc.cryxtal.org/ci-img/git-curl-jq:latest'

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  convert-png:
    image: *emoji_build_image
    commands:
      - ./.ci-make.sh twemoji-png128

  build-prep:
    image: *emoji_build_image
    commands:
      - ./.ci-make.sh noto-patch
      - ./.ci-make.sh twemoji-prep

  emoji-build:
    image: *emoji_build_image
    commands:
      - ./.ci-make.sh debian-add_vs_cmap
      - ./.ci-make.sh emoji-build

  magisk-build:
    image: *emoji_build_image
    commands:
      - ./.ci-make.sh magisk-prep
      - ./.ci-make.sh magisk-zip

  gen-sha256:
    image: *sha256_image
    commands:
      - ./.ci-sha256.sh magisk-twemoji

  upload-crystalcommit:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://sc.cryxtal.org
      files:
        - "magisk-twemoji-*.zip"
        - "magisk-twemoji-*.zip.sha256"
      api_key:
        from_secret: sc_api_key
      prerelease: false
      skip_verify: true
    when:
      event: [ tag ]
