labels:
  platform: linux/amd64

when:
  event: [ push, tag ]

variables:
  - &emoji_build_image 'debian:bookworm'

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  emoji-build:
    image: *emoji_build_image
    environment:
      - DEBIAN_FRONTEND=noninteractive
    commands:
      - ./.ci-make.sh debian-deps
      - ./.ci-make.sh noto-patch
      - ./.ci-make.sh twemoji-prep
      - ./.ci-make.sh emoji-build
      - ls -al

  magisk-build:
    image: *emoji_build_image
    environment:
      - DEBIAN_FRONTEND=noninteractive
    commands:
      - ./.ci-make.sh zip-deps
      - ./.ci-make.sh magisk-prep
      - ./.ci-make.sh magisk-zip

  gen-sha256:
    image: sc.cryxtal.org/ci-img/git-curl-jq:latest
    commands:
      - ./.ci-sha256.sh magisk-twemoji

  upload-crystalcommit:
    image: woodpeckerci/plugin-gitea-release
    settings:
      base_url: https://sc.cryxtal.org
      files:
        - "magisk-twemoji-*.zip"
        - "magisk-twemoji-*.zip.sha256"
      api_key:
        from_secret: sc_api_key
      prerelease: true
      skip_verify: true
    when:
      event: [ tag ]
